-- Create the service_charges table
CREATE TABLE IF NOT EXISTS public.service_charges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name TEXT NOT NULL UNIQUE,
    charge_per_min INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add comments to the table and columns for clarity (optional)
COMMENT ON TABLE public.service_charges IS 'Stores the charges for different services like chat, audio call, video call.';
COMMENT ON COLUMN public.service_charges.service_name IS 'Name of the service (e.g., Chat, Audio Call, Video Call).';
COMMENT ON COLUMN public.service_charges.charge_per_min IS 'Charge for the service in smallest currency unit (e.g., paisa, cents) per minute. Or as a whole number if representing Rupees directly.';


-- Insert initial service charges
-- Ensure service_name is unique to avoid errors if script is run multiple times without proper checks
-- Or use ON CONFLICT DO NOTHING / ON CONFLICT DO UPDATE if you prefer
INSERT INTO public.service_charges (service_name, charge_per_min) VALUES
    ('Chat', 10)
ON CONFLICT (service_name) DO NOTHING;

INSERT INTO public.service_charges (service_name, charge_per_min) VALUES
    ('Audio Call', 10)
ON CONFLICT (service_name) DO NOTHING;

INSERT INTO public.service_charges (service_name, charge_per_min) VALUES
    ('Video Call', 15)
ON CONFLICT (service_name) DO NOTHING;

-- Grant permissions if necessary (adjust role as needed)
-- By default, tables created by a user are accessible to that user.
-- If you need broader access, for example, for the 'authenticated' role:
-- ALTER TABLE public.service_charges ENABLE ROW LEVEL SECURITY; -- If not already enabled for your project
-- CREATE POLICY "Allow authenticated read access to service charges"
-- ON public.service_charges FOR SELECT
-- TO authenticated
-- USING (true);